### ISSUE TITLE
wxWidgets is not available as a wheel for ubuntu 22.04 (and maybe other new distros)

### ISSUE THREAD

**Issue by nm17** [eoyilmaz/displaycal-py3#101]
I don't want to wait a full day for it to stop compiling...

**Comment by eoyilmaz** [comment]
I'm on Pop!_OS 22.04 and I can install it without a problem. What is your problem exactly? Time or is it impossible to install?

**Comment by nm17** [comment]
@eoyilmaz if you pip install wxPython in a virtualenv it takes forever to compile

**Comment by eoyilmaz** [comment]
You can find the wheels here:

```python
https://wxpython.p5k.org/wxPython-4.1.1-cp${{ env.py_version }}-cp${{ env.py_version }}-linux_x86_64.whl
```

To understand it better, how much time you are talking here?

**Comment by p5k369** [comment]
Hey @nm17 wxPython depends on system provided libraries and therefor has to be compiled for your machine. As @eoyilmaz pointed out it might be possible that displaycal runs with the wheels on your specific machine because you are on ubuntu 22.04 and those are the wheels that displaycal uses for testing for exact the same reason.

However I do not think that displaycal can (and should) provide dependency wheels for every distro out there. This is more an issue for https://github.com/wxWidgets/Phoenix

**Comment by eoyilmaz** [comment]
@p5k369 agree and it should take ~10 minutes to compile in most of the computers.

**Comment by eoyilmaz** [comment]
closing this ticket now.
