### ISSUE TITLE
Parsing of settings is broken

### ISSUE THREAD

**Issue by ledoge** [eoyilmaz/displaycal-py3#171]
Selecting an entry in the "Settings" dropdown at the top should set the values under the Calibration, Profiling, 3D LUT and Verification tabs accordingly. For example, selecting sRGB should set the tone curve to sRGB under Calibration. Instead, all fields just appear to be set to their default values.

I tracked this down to the code here: https://github.com/eoyilmaz/displaycal-py3/blob/main/DisplayCAL/display_cal.py#L17900 . `options_displaycal` contains strings, but the parser tries to compare them to byte strings, which is why none of the settings are actually applied.

**Comment by p5k369** [comment]
Hey @ledoge, take a look at #177. That should fix the problem. Besides the byte-str comparison we also had an error when setting the cfg values. However I think @eoyilmaz should take a closer look at those byte-str to str comparison issue because we switched them to byte-str on purpose but I could not figure out why.

**Comment by eoyilmaz** [comment]
Hey guys, I'm a little busy these days, sorry for being late of answering, Hopefully this week I'll look in to code, btw, thank you @p5k369 you're doing great.

**Comment by p5k369** [comment]
With windows10 the tabs are updated according to the setting chosen in the dropdown. However on linux the tabs sometimes are updated but the settings inside the last 3 tabs are not set correctly.
