### ISSUE TITLE
displaycal-py3 instructions fail Ubuntu 22.04LTS current

### ISSUE THREAD

**Issue by ykarant** [eoyilmaz/displaycal-py3#191]
[displaycal-build-fail.txt](https://github.com/eoyilmaz/displaycal-py3/files/9641594/displaycal-build-fail.txt)

please reply to ykarant@gmail.com

**Comment by p5k369** [comment]
Hey @ykarant, this can be solved in different ways. 
- if you want to stay with the main branch then you need to install `attrdict3` you basically get the error already discussed in #155.
However I would recommend:
- clone the dev branch instead of the main branch at the moment you do this by `git clone -b dev https://github.com/eoyilmaz/displaycal-py3`
- you also could download the tarball of the latest release at https://github.com/eoyilmaz/displaycal-py3/releases/tag/3.9.8

Hey @eoyilmaz we made a mistake with the last release and forgot to merge dev into the main branch. What do you think is the best solution? Make a new version and merge the complete dev or pick the last relevant commit, I think that has to be [b600b649490ebed80cb4da562fdbd6234fab689f](https://github.com/eoyilmaz/displaycal-py3/commit/b600b649490ebed80cb4da562fdbd6234fab689f).

**Comment by p5k369** [comment]
Fixed with latest release.
