### ISSUE TITLE
Please run with a Framework build of python, and only when you are logged in on the main display of your Mac

### ISSUE THREAD

**Issue by dprestegard** [eoyilmaz/displaycal-py3#238]
I built the app by following the guide exactly on macOS 13.0.1. When I try to actually run displaycal I get this:

```shell
displaycal-py3 on  main via 🐍 v3.9.6 (displaycal_venv) on ☁️  (us-west-2) took 5s 
❯ displaycal
Acquired lock file: <DisplayCAL.main.AppLock object at 0x100e639d0>
displaycal 3.9.10 2023-03-08T18:33:29Z
Mac OS X 13.0.1 arm64
Python 3.9.6 (default, Oct 18 2022, 12:41:40) 
[Clang 14.0.0 (clang-1400.0.29.202)]
CA file /Users/Derek.L.Prestegard/displaycal_venv/lib/python3.9/site-packages/certifi/cacert.pem
Faulthandler 
wxPython 4.2.0 osx-cocoa (phoenix) wxWidgets 3.2.0
Encoding: utf-8
File system encoding: utf-8
Existing client using port 15411
Connecting to 15411...
Connection to 127.0.0.1:15411 failed: [Errno 61] Connection refused
listening
writing to lock file: port: 51988
Starting up...
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
Ran application exit handlers
```

I'm not as familiar with the specifics of running Python GUI apps on macOS (as in.. I've literally never once done this lol) so maybe I'm missing something basic?

**Comment by mistryrn** [comment]
I just ran into the same error, was getting this:
```
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```
after building the app and trying to run it on my Intel Mac running macOS 12.6.3.

What worked for me was re-installing python with the `--enable-framework` flag.

For context, my python environment was set up using `brew`, `pyenv`, and `pyenv-virtualenv` (this guide is great: https://towardsdatascience.com/python-how-to-create-a-clean-learning-environment-with-pyenv-pyenv-virtualenv-pipx-ed17fbd9b790).

Since my python was installed via pyenv, uninstalling and reinstalling with the required flag looked like:
```bash
pyenv uninstall 3.10.10
PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.10.10
```

Once python was re-installed, I followed the steps in the README to build displaycal, and this time it launched 🙌 

Note that macOS throws a ton of Security warnings about packages in the app being unverified. It was annoying, but I had to click "Cancel" on those warnings, then go to `System Preferences > Security & Privacy > General` and click "Allow" each time one came up, then relaunch the app. Once I did that about half a dozen times the app finally launched without throwing any security warnings and I was able to do a calibration.

Hope this helps!

**Comment by eoyilmaz** [comment]
> Note that macOS throws a ton of Security warnings about packages in the app being unverified. It was annoying, but I had to click "Cancel" on those warnings, then go to System Preferences > Security & Privacy > General and click "Allow" each time one came up, then relaunch the app.

you can use `xattr -c *` under `Argyll_v3.x.x/bin/` folder to reset all the attributes, this should prevent the security questions.

and I cannot produce the other problem under my Macbook Pro M1 Pro and Macbook Pro M3 Max. And we'll release MacOS packages with the new release this week...

Closing...
