### ISSUE TITLE
DisplayCal .dmg for x86?

### ISSUE THREAD

**Issue by decayedxistence** [eoyilmaz/displaycal-py3#431]
**EDIT** Never mind. I just realized this is a version for Mac Silicon. Are there any plans for older intel Macs?

Congrats on getting a .dmg up for Mac! I just downloaded it and tried installed. I noticed before dragging the DisplayCal Icon into the applications folder that it had a one circle with a line through it. It installed fine, but then when I try to open the application, I get a notification that the app is not compatible with my OS. If I open the package contents and try clicking on the DisplayCal executable file, I get a notification that says this package is damaged and to move it to the trash.

 - OS: Mac OS Sonoma (Intel)
 - Python Version: 3.13
 - ArgyllCMS Version: 3.3
 - DisplayCAL Version: 3.9.14
 - 
![Screenshot 2024-10-15 at 11 19 02 PM](https://github.com/user-attachments/assets/7a7f0568-b109-48da-9dd1-26db7073f85a)

![Screenshot 2024-10-15 at 11 20 33 PM](https://github.com/user-attachments/assets/0bdba23b-6786-472b-be92-b72b4770b768)

**Comment by eoyilmaz** [comment]
> **EDIT** Never mind. I just realized this is a version for Mac Silicon. Are there any plans for older intel Macs?

It would be lovely if you can generate one and send it over to me:

1 - Fristly install the requirements if you didn't already done it before:

```shell
brew install glib gtk+3 python@3.12
```

2- Build DisplayCAL:

```shell
cd ~
git clone https://www.github.com/eoyilmaz/displaycal-py3
cd displaycal-py3
SYSTEM_PYTHON=python3.12 make venv build install
source ./.venv/bin/activate
python setup.py py2app
```

3- That should generate `~/displaycal-py3/dist/py2app.macosx-14.0-arm64-py3.12/DisplayCAL-3.9.14` folder, you can put a link to the `/Applications` for people to easily drag & drop the app in to their Applications folder:

```shell
cd ~/displaycal-py3/dist/py2app.macosx-14.0-arm64-py3.12/DisplayCAL-3.9.14
ln -s /Applications
```

4- Use `Disk Utility.app` to generate a `dmg` file, by `File -> New Image -> Image From Folder...` and selecting the `~/displaycal-py3/dist/py2app.macosx-14.0-arm64-py3.12/DisplayCAL-3.9.14` folder.

5- Now you can rename the `dmg` file to `DisplayCAL-3.9.14_macOS_x86.dmg` and send it over to me so that I can share it with people.

🤔  I think there is a way of doing it through my Apple Silicon Macbook but it would mess up my brew library...

**Comment by CandiumQ** [comment]
Ah was just about to post the same issue. On an intel mac myself!

**Comment by eoyilmaz** [comment]
The above instructions are good for generating the `DisplayCAL.app` and a `dmg` image. I'm also updating the install instructions to contain this information.

**Comment by eoyilmaz** [comment]
I think we should be able to generate these over GitHub actions as a hook for the merge to main branch.

**Comment by VgerTest** [comment]
I hope I made it properly, DisplayCAL-3.9.14_macOS_x86.dmg
https://1fichier.com/?3elfzklhrdm2xaon4cwa
Seems to work on my intel setup: Loaded previously generated profile by src DIsplayCAL-py3, ran profile verification, ran calibrated/uncalibrated console report.

**Comment by eoyilmaz** [comment]
Oh thanks for the image... Let me download it and put it in to GitHub. (Removing the download link in your comment).

**Comment by eoyilmaz** [comment]
This 1fichier.com is reaaaally slow... still downloading...

**Comment by VgerTest** [comment]
I'll try to do the same for 3.9.15

**Comment by eoyilmaz** [comment]
I already created one, but doesn't seem to be working, complaining about `libffi.8.dylib` not being found.

**Comment by eoyilmaz** [comment]
ah thank you for the DMG, I'll replace it with yours, and for the bug report, let me create a new issue 👍
